title: "Xiao-Su (Frank) Hu"
description: "Data Scientist | Machine Learning Expert | Neuroimaging | Healthcare"
url: "https://xiaosuhu.github.io"
baseurl: ""

remote_theme: daviddarnes/alembic

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Author settings
author:
  name: "Xiao-Su (Frank) Hu"
  email: "xiaosuhu@umich.edu"
  github: "xiaosuhu"
  linkedin: "xiaosu-hu-1458a656"

# Navigation - CORRECT ORDER
navigation:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Publications  
    url: /publications/
  - title: Contact
    url: /contact/

# Social links (appear in footer)
social:
  - title: GitHub
    url: https://github.com/xiaosuhu
    icon: github
  - title: LinkedIn  
    url: https://www.linkedin.com/in/xiaosu-hu-1458a656
    icon: linkedin
  - title: Google Scholar
    url: https://scholar.google.com/citations?user=wody7D8AAAAJ&hl=en
    icon: scholar

# Sass settings
sass:
  style: compressed

# Disable default collections
collections:
  posts:
    output: false
  elements:
    output: false